#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


## How does this game work?
# GAME-LOOP
#  - check for keyboard input
#  - update user
#  - update ghosts
#  - paint to screen
# REPEAT

## GLOBALS
# Base dir for the game
SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"
# Last registered key from keyboard
KEY_READ=

# Game loop variables
FRAME_TIMER=0
FRAME_UPDATE_INTERVAL=100  # Move every 0.1 second
FRAME_UPDATE_INTERVAL_US=$(( FRAME_UPDATE_INTERVAL * 1000 ))

RUNNING=1
DEBUG=
DEBUG_FLAGS=()
SCORE=0

source "$SCRIPT_DIR/lib/keyboard"
source "$SCRIPT_DIR/lib/map"
source "$SCRIPT_DIR/lib/statusbar"
source "$SCRIPT_DIR/lib/timer"
source "$SCRIPT_DIR/lib/ghosts"
source "$SCRIPT_DIR/lib/pacman"

setup() {
	screen-erase-all
	screen-hide-cursor
	statusbar-setup
	keyboard::setup

	echo "" > pacman.log
}

teardown() {
	screen-show-cursor
}

toggle-debug() {
    [[ -z $DEBUG ]] && DEBUG=1 || unset DEBUG

	# Toggle FPS debugging
	timer-debug
}

update-keyboard() {
	local new_key
	read -rs -u "$pipefd" -t .001 new_key
	[[ -n $new_key ]] && KEY_READ=$new_key

	case $KEY_READ in
		"key-home")
			toggle-debug
			;;
		"key-end")
			unset RUNNING
			;;
		"key-left" | "a")
			pacman-set-direction "left"
			;;
		"key-right" | "d")
			pacman-set-direction "right"
			;;
		"key-up" | "w")
			pacman-set-direction "up"
			;;
		"key-down" | "s")
			pacman-set-direction "down"
			;;
		[1-9])
			[[ -z ${DEBUG_FLAGS[$KEY_READ]} ]] && DEBUG_FLAGS["$KEY_READ"]="1" || DEBUG_FLAGS["$KEY_READ"]=""
			;;
	esac
	KEY_READ=
}

update-frame() {
	## Measure time since last move, only move every FRAME_UPDATE_INTERVAL_US microsecs
	local frame_time
	frame_time=$(timer-get-elapse-time)
	FRAME_TIMER=$(( FRAME_TIMER + frame_time ))

	# No movement yet - exit the function
	[[ $FRAME_TIMER -lt $FRAME_UPDATE_INTERVAL_US ]] && return

	# Reset elapse timer
	FRAME_TIMER=0

	# Game updates on every move
	pacman-update
	ghosts::update
}

update-screen() {
	screen-pos-home
	map::print-map
}

update-statusbar() {
	local fps=$(timer-get-fps)
	local clock
	printf -v clock '%(%Y-%m-%d %H:%M:%S)T\n' -1

	local content="Score: $SCORE"
	[[ -n $DEBUG ]] && [[ -n ${DEBUG_FLAGS[1]} ]] && content="$content | Avg. FPS: $fps"
	[[ -n $DEBUG ]] && [[ -n ${DEBUG_FLAGS[2]} ]] && content="$content | Direction: $PACMAN_DIRECTION"
	[[ -n $DEBUG ]] && [[ -n ${DEBUG_FLAGS[3]} ]] && content="$content | Cheese count: $__MAP_CHEESE_COUNT"
	[[ -n $DEBUG ]] && [[ -n ${DEBUG_FLAGS[4]} ]] && content="$content | POS: ${__PACMAN_POS[0]},${__PACMAN_POS[1]}"
	[[ -n $DEBUG ]] && [[ -n ${DEBUG_FLAGS[5]} ]] && content="$content | Cell Content: $(map::get-cell-type ${__PACMAN_POS[0]} ${__PACMAN_POS[1]})"
	[[ -n $DEBUG ]] && [[ -n ${DEBUG_FLAGS[9]} ]] && content="$content | Clock: $clock"

	statusbar-update "$content"
}

main() {
	setup

	# Read in only map I have for now
	map::read "$SCRIPT_DIR/maps/map1"

	# GAME LOOP
	local i=0
	timer-start

	# Game loop continues until RUNNING is set!
	while [[ -n $RUNNING ]]; do
		# Input update
		update-keyboard

		# Game update
		update-frame

		# Output update
		update-screen

		# Update user friend statusbar
		update-statusbar

		# Game done?
		map::is-clear && RUNNING=""

		timer-tick

		# Frame count
		((i=i+1))
	done;

	# total time is recorded in number of microseconds since timer started
	local total_time=$(timer-stop)
	local fps=$(( (i * 1000 * 1000) / total_time ))
	screen-pos-at 0 32
	echo "Total Frames: $i | Total Time: ${total_time}us | Avg. FPS: $fps"

	teardown
}

main
