#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.


## How does this game work?
# GAME-LOOP
#  - check for keyboard input
#  - update user
#  - update ghosts
#  - paint to screen
# REPEAT

## GLOBALS
# Base dir for the game
SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"
# Last registered key from keyboard
KEY_READ=
# PACMAN stuff
PACMAN_POS=(4 14)
PACMAN_OLD_POS=(4 14)
declare -A PACMAN_ICONS
PACMAN_ICONS[left]="Ↄ"
PACMAN_ICONS[right]="C"
PACMAN_ICONS[up]="U"
PACMAN_ICONS[down]="∩"
PACMAN_ICON=${PACMAN_ICONS[right]}
PACMAN_EMPTY_ICON=" "
PACMAN_DIRECTION=""
PACMAN_ELAPSE_TIMER=0
PACMAN_MOVE_EVERY_MS=100  # Move every 0.5 second
PACMAN_MOVE_EVERY_US=$(( PACMAN_MOVE_EVERY_MS * 1000 ))

# Game loop variables
RUNNING=1
DEBUG=
DEBUG_FLAGS=()
SCORE=0

source "$SCRIPT_DIR/lib/keyboard"
source "$SCRIPT_DIR/lib/map"
source "$SCRIPT_DIR/lib/statusbar"
source "$SCRIPT_DIR/lib/timer"
source "$SCRIPT_DIR/lib/ghosts"

setup() {
	screen-erase-all
	screen-hide-cursor
	statusbar-setup
	keyboard-setup

	echo "" > pacman.log
}

teardown() {
	screen-show-cursor
}

update-keyboard() {
	local new_key
	read -rs -u "$pipefd" -t .001 new_key
	[[ -n $new_key ]] && KEY_READ=$new_key
}

handle-keyboard() {
	case $KEY_READ in
		"key-home")
			toggle-debug
			;;
		"key-end")
			unset RUNNING
			;;
		"key-left" | "a")
			PACMAN_DIRECTION="left"
			;;
		"key-right" | "d")
			PACMAN_DIRECTION="right"
			;;
		"key-up" | "w")
			PACMAN_DIRECTION="up"
			;;
		"key-down" | "s")
			PACMAN_DIRECTION="down"
			;;
		[1-9])
			[[ -z ${DEBUG_FLAGS[$KEY_READ]} ]] && DEBUG_FLAGS["$KEY_READ"]="1" || DEBUG_FLAGS["$KEY_READ"]=""
			;;
	esac
	KEY_READ=
}

update-frame() {
	## Measure time since last move, only move every PACMAN_MOVE_EVERY_US microsecs
	local frame_time
	frame_time=$(timer-get-elapse-time)
	PACMAN_ELAPSE_TIMER=$(( PACMAN_ELAPSE_TIMER + frame_time ))

	# No movement yet - exit the function
	[[ $PACMAN_ELAPSE_TIMER -lt $PACMAN_MOVE_EVERY_US ]] && return

	# Reset elapse timer
	PACMAN_ELAPSE_TIMER=0

	update-pacman
	update-ghosts
}

update-pacman() {
	# Store old position - needed when drawing to erase old pacman icon
	PACMAN_OLD_POS=("${PACMAN_POS[@]}")

	# Update position according to direction
	local PM_COL="${PACMAN_POS[0]}"
	local PM_ROW="${PACMAN_POS[1]}"
	case $PACMAN_DIRECTION in
		left)  	((PM_COL-=1));;
		right) 	((PM_COL+=1));;
		up)		((PM_ROW-=1));;
		down)	((PM_ROW+=1));;
		*)		return;; # On start pacman doesn't have a direction
	esac
	# Wrap around edge of maps, ensures both under and over shoot is kept within maps size
	((PM_COL = (PM_COL + 28) % 28))
	((PM_ROW = (PM_ROW + 31) % 31))

	## Handle collision with walls
	local cell_type=$(map-get-cell-type $PM_COL $PM_ROW)
	case "$cell_type" in
		"$MAP_CELL_WALL")
			# Colliding with wall, do nothing
			return
			;;
		"$MAP_CELL_CHEESE")
			# Hitting Cheese - score a point
			((SCORE+=1))
			;;
		"$MAP_CELL_BONUS")
			# Hitting a bonus - score a point AND activate bonus period
			((SCORE+=1))
			# TODO: Start Bonus Period
			;;
		"$MAP_CELL_EMPTY")
			# Do nothing, just move
			;;
	esac

	# Update position
	PACMAN_POS=("$PM_COL" "$PM_ROW")
	# Update Icon for direction
	PACMAN_ICON=${PACMAN_ICONS[$PACMAN_DIRECTION]}
}

update-ghosts() {
	ghosts-update
}

update-map() {
	# Erase old position of pacman
	local PM_OLD_COL="${PACMAN_OLD_POS[0]}"
	local PM_OLD_ROW="${PACMAN_OLD_POS[1]}"
	map-set-cell-content "$PM_OLD_COL" "$PM_OLD_ROW" "$PACMAN_EMPTY_ICON"

	local PM_COL="${PACMAN_POS[0]}"
	local PM_ROW="${PACMAN_POS[1]}"
	map-set-cell-content "$PM_COL" "$PM_ROW" "$PACMAN_ICON"
}

toggle-debug() {
    [[ -z $DEBUG ]] && DEBUG=1 || unset DEBUG

	# Toggle FPS debugging
	timer-debug
}

print-map() {
	screen-pos-home
	map-print-map
}

update-statusbar() {
	local fps=$(timer-get-fps)
	local clock
	printf -v clock '%(%Y-%m-%d %H:%M:%S)T\n' -1

	local content="Score: $SCORE"
	[[ -n $DEBUG ]] && [[ -n ${DEBUG_FLAGS[1]} ]] && content="$content | Avg. FPS: $fps"
	[[ -n $DEBUG ]] && [[ -n ${DEBUG_FLAGS[2]} ]] && content="$content | Direction: $PACMAN_DIRECTION"
	[[ -n $DEBUG ]] && [[ -n ${DEBUG_FLAGS[3]} ]] && content="$content | Cheese count: $__MAP_CHEESE_COUNT"
	[[ -n $DEBUG ]] && [[ -n ${DEBUG_FLAGS[4]} ]] && content="$content | POS: ${PACMAN_POS[0]},${PACMAN_POS[1]}"
	[[ -n $DEBUG ]] && [[ -n ${DEBUG_FLAGS[5]} ]] && content="$content | Cell Content: $(map-get-cell-type ${PACMAN_POS[0]} ${PACMAN_POS[1]})"
	[[ -n $DEBUG ]] && [[ -n ${DEBUG_FLAGS[9]} ]] && content="$content | Clock: $clock"

	statusbar-update "$content"
}

main() {
	setup

	map-read "$SCRIPT_DIR/maps/map1"

	# GAME LOOP
	local i=0
	timer-start
	while [[ -n $RUNNING ]]; do
		update-keyboard
		handle-keyboard

		update-frame
		update-map
		print-map

		map-is-clear && RUNNING=""

		update-statusbar

		timer-tick
		((i=i+1))
	done;

	local total_time=$(timer-stop)
	local fps=$(( (i * 1000 * 1000) / total_time ))
	echo "Total Frames: $i | Total Time: ${total_time}us | Avg. FPS: $fps"

	teardown
}

main

### [torsten@rainier:/home/torsten/Coding/torstenchr/bash_pacman]$ ./analyse.py trace.log 
### Total wall time in log: 217471.625 ms
### Function, Total_ms, Percent, Calls, Avg_ms_per_call
### map-get-cell-type,27693.698,12.73%,7888,3.511
### map-set-cell-content,25898.499,11.91%,7402,3.499
### map-print-map,22153.933,10.19%,6659,3.327
### _map-print-full,17626.689,8.11%,5392,3.269
### map-get-cell-content,16949.421,7.79%,4928,3.439
### screen-pos-at,16259.362,7.48%,4914,3.309
### _map-transform,11664.346,5.36%,3750,3.110
### update-statusbar,10045.483,4.62%,2964,3.389
### main,8791.436,4.04%,2480,3.545
### _move-ghost,8763.776,4.03%,2706,3.239
### update-frame,6981.022,3.21%,1974,3.536
### ghosts-update,6659.562,3.06%,1968,3.384
### screen_write_to_reserved_line,6623.878,3.05%,1976,3.352
### statusbar-update,5765.529,2.65%,1729,3.335
### update-map,5104.128,2.35%,1482,3.444
### [torsten@rainier:/home/torsten/Coding/t