#!/usr/bin/env bash

SCRIPT_DIR="$(dirname ${BASH_SOURCE[0]})"

# set -x

fun_a() {
    declare -n oldpos="$1"
    declare -n direction="$2"

    ((oldpos[0]++))
    ((oldpos[1]++))

    echo "$direction"
}

fun_b() {
    local -n foo="$1"
    local -n bar="$2"

    fun_a "foo" "bar"
}


the_pos=(14 14)
the_dir="left"

echo "the_pos = ${the_pos[*]}"
fun_b "the_pos" "the_dir"
echo "the_pos = ${the_pos[*]}"
