#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# PRAGMA: Use once and only as sourced
if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The file ${BASH_SOURCE[0]} can only be sourced!"; exit 1; fi
if [ -n "$SOURCE_GHOST" ]; then return; fi

source "$SCRIPT_DIR/lib/map"

# __GHOST_POSITION=(14 14)
# __GHOST_DIRECTION="up"
ghost::init() {
	local init_pos=("$1" "$2")
	map::init-character "${init_pos[@]}" "$MAP_CELL_GHOST"
}

ghost::_move() {
    local -n position="$1"
	local -n direction="$2"

	local cell_pos_a cell_pos_b cell_pos_c
	local cell_type_a cell_type_b cell_type_c

	## Ghost can potentially move up to 3 new directions at each point:
	##     B
	##    ║∙║
	##	 ═╝∙╚═
	##	A∙∙#∙∙C
	##	 ═╗∙╔═
 	##	  ║∙║
	##     D
	## In the caculations below the ghost is alway coming from direction D
	## and can potentially go towards A, B or C (but never back)
	## The map can be rotated to fit the actual direction, but the calculation
	## logic remains the same.
	## If a direction contains a wall it is removed from potential paths to
	## take.
	## If more than one option exists, flip a coin for the direction.

	local new_direction
	case "$direction" in
		"up")    new_direction=("left" "right" "up");;
		"down")  new_direction=("left" "right" "down");;
		"left")  new_direction=("left" "up" "down");;
		"right") new_direction=("right" "up" "down");;
	esac

	cell_pos_a=( ${ map::new-position "${position[@]}" "${new_direction[0]}"; } )
	cell_pos_b=( ${ map::new-position "${position[@]}" "${new_direction[1]}"; } )
	cell_pos_c=( ${ map::new-position "${position[@]}" "${new_direction[2]}"; } )
	cell_type_a=${ map::get-cell-type "${cell_pos_a[@]}"; }
	cell_type_b=${ map::get-cell-type "${cell_pos_b[@]}"; }
	cell_type_c=${ map::get-cell-type "${cell_pos_c[@]}"; }

	local cells=()
	[[ "$cell_type_a" != "$MAP_CELL_WALL" ]] && cells+=("a")
	[[ "$cell_type_b" != "$MAP_CELL_WALL" ]] && cells+=("b")
	[[ "$cell_type_c" != "$MAP_CELL_WALL" ]] && cells+=("c")

	## TODO: Handle if a direction can see Pacman, prefer that route over all other

	# Choose a random path based on possible options
	local coin=$(( RANDOM % ${#cells[@]} ))
	case "${cells[$coin]}" in
		"a")
			direction="${new_direction[0]}"
			position=( "${cell_pos_a[@]}" )
			;;
		"b")
			direction="${new_direction[1]}"
			position=( "${cell_pos_b[@]}" )
			;;
		"c")
			direction="${new_direction[2]}"
			position=( "${cell_pos_c[@]}" )
			;;
	esac
}

ghost::update() {
	# references to variables living in scope outside of here
    local -n ghost_position="$1"
	local -n ghost_direction="$2"
	local oldpos=("${ghost_position[@]}")

    ghost::_move "ghost_position" "ghost_direction"
    map::move-character "${oldpos[@]}" "${ghost_position[@]}" "$MAP_CELL_GHOST"
}

export SOURCE_GHOST=1