#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# PRAGMA: Use once and only as sourced
if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The utils can only be sourced!"; exit 1; fi
if [ -n "$SOURCE_GHOSTS" ]; then return; fi

source "$SCRIPT_DIR/lib/map"

__GHOST_POSITION=(14 14)
__GHOST_OLD_POSITION=
__GHOST_DIRECTION="up"
__GHOST_ICON="#"

_move-ghost() {
	# Store old position - needed when drawing to erase old pacman icon
	__GHOST_OLD_POSITION=("${__GHOST_POSITION[@]}")

	# Update position according to direction
	local COL="${__GHOST_POSITION[0]}"
	local ROW="${__GHOST_POSITION[1]}"
	case $__GHOST_DIRECTION in
		left)  	((COL-=1));;
		right) 	((COL+=1));;
		up)		((ROW-=1));;
		down)	((ROW+=1));;
	esac
	# Wrap around edge of maps, ensures both under and over shoot is kept within maps size
    # TODO: Read MAP width/height
	((COL = (COL + 28) % 28))
	((ROW = (ROW + 31) % 31))

	## Handle collision with walls
	local cell_type=$(map-get-cell-type $COL $ROW)
	case "$cell_type" in
		"$MAP_CELL_WALL")
			# Colliding with wall, change direction
			return
			;;
	esac

	# Update position
	__GHOST_POSITION=("$COL" "$ROW")
}

ghosts-update() {
    local col row

	col="${__GHOST_POSITION[0]}"
	row="${__GHOST_POSITION[1]}"
    map-get-cell-content "$col" "$row" "$__GHOST_ICON"

    _move-ghost

	col="${__GHOST_POSITION[0]}"
	row="${__GHOST_POSITION[1]}"
    map-set-cell-content "$col" "$row" "$__GHOST_ICON"
}


export SOURCE_GHOSTS=1