#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# PRAGMA: Use once and only as sourced
if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The keyboard can only be sourced!"; exit 1; fi
if [ -n "$SOURCE_KEYBOARD" ]; then return; fi

source "$SCRIPT_DIR/lib/utils"
source "$SCRIPT_DIR/lib/traps"

_keyboard_read_pid=
declare -A __KEYBOARD_CALLBACKS

## Initializes the program for reading from the terminal keyboard.
## In order to recieve inputs use the keyboard::register function
##  to associate a key with a callback function
keyboard::init() {
	local PIPE
	# open the terminal for keyboard input
	exec {keyboardfd}</dev/tty || fatal 'no terminal detected'

	# TODO: Take this as an argument??
	PIPE=$(mktemp_fifo)
	exec {pipefd}<>"$PIPE" || fatal "failed to open pipe $PIPE"

    keyboard::_read <&"$keyboardfd" &
	_keyboard_read_pid=$!
}

keyboard::_read() {
    ## Proudly copied from Dave Eddy (YSAP.sh): https://github.com/bahamas10/nightfall-tui/tree/main
	local escape_char=$'\u1b'
	while true; do
		local data=
		read -rsn1 data 2>/dev/null || return
		if [[ $data == "$escape_char" ]]; then
			read -rsn2 data 2>/dev/null || return
		fi

		local output=
		case "$data" in
			'[A' ) output='key-up';;
			'[B' ) output='key-down';;
            '[C' ) output='key-right';;
            '[D' ) output='key-left';;
            '[F' ) output='key-end';;
			'[H' ) output='key-home';;
			'[2' ) output='key-insert';;
			'[3' ) output='key-delete';;
			'[4' ) output='key-pgup';;
			'[6' ) output='key-pgdown';;
			''   ) output='key-enter';;
			'['* ) log "Unknown escaped key: $data";;
            *    ) output="$data"
		esac

		if [[ -n $output ]]; then
			echo "$output" >&"$pipefd"
		fi
	done
}

## This function SHOULD be called from main thread as it triggers callbacks
## to subscribers. If called from other threads the callbacks are also called
## from this thread. 
keyboard::check-for-input() {
	local new_key
	read -rs -u "$pipefd" -t .001 new_key

	# Nothing read, exit
	[[ -z $new_key ]] && return

	# No callbacks registered for key
	[[ -z "${__KEYBOARD_CALLBACKS[$new_key]}" ]] && return

	while read -d "," -r callback
	do
		$callback "$new_key"
	done <<< "${__KEYBOARD_CALLBACKS[$new_key]}"
}

keyboard::_dump-register() {
	local key

	for key in "${!__KEYBOARD_CALLBACKS[@]}"; do
		echo "Registrations for key: '$key': '${__KEYBOARD_CALLBACKS[$key]}'"
	done
}

keyboard::_register-key() {
	local new_callback="$1"
	local key="$2"

	local callback_list="${__KEYBOARD_CALLBACKS[$key]}"
	# Do not add same callback function twice
	[[ "$callback_list" =~ $new_callback ]] && return

	callback_list="$new_callback,$callback_list"
	__KEYBOARD_CALLBACKS[$key]="$callback_list"
}

## Register a set of keys to a callback function. If the key is pressed the check-for-input
## method will ensure the callbacks for the keys are called.
# $1:  Callback function
# $2+: list of keys to register
keyboard::register-keys() {
	local callback="$1"; shift
	local keys=("$@")

	local key
	for key in "${keys[@]}"; do
		keyboard::_register-key "$callback" "$key"
	done
}

keyboard::_cleanup() {
	if [[ -n $_keyboard_read_pid ]]; then
		kill "$_keyboard_read_pid"
	fi
}

trap::add keyboard::_cleanup EXIT

export SOURCE_KEYBOARD=1