#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# PRAGMA: Use once and only as sourced
if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The keyboard can only be sourced!"; exit 1; fi
if [ -n "$SOURCE_KEYBOARD" ]; then return; fi

source "$SCRIPT_DIR/lib/utils"
source "$SCRIPT_DIR/lib/traps"

_keyboard_read_pid=

## Setup the program for reading from the terminal keyboard.
## It opens a pipe and allow for reading from FD=3
## The content of the keyboard is written into FD=3
keyboard-setup() {
	local PIPE
	# open the terminal for keyboard input
	exec 4</dev/tty || fatal 'no terminal detected'

	# TODO: Take this as an argument??
	PIPE=$(mktemp_fifo)
	exec 3<>"$PIPE" || fatal "failed to open pipe $PIPE"

    _read-keyboard <&4 &
	_keyboard_read_pid=$!
	echo "_keyboard_read_pid: $_keyboard_read_pid"
}

_read-keyboard() {
    ## Proudly copied from Dave Eddy (YSAP): https://github.com/bahamas10/nightfall-tui/tree/main
	local escape_char=$'\u1b'
	while true; do
		local data=
		read -rsn1 data 2>/dev/null || return
		if [[ $data == "$escape_char" ]]; then
			read -rsn2 data 2>/dev/null || return
		fi

		local output=
		case "$data" in
			'[A') output='key-up';;
			'[B') output='key-down';;
            '[C') output='key-right';;
            '[D') output='key-left';;
            '[F') output='key-end';;
			'[H') output='key-home';;
			''      ) output='key-enter';;
            *       ) output="$data"
		esac

		if [[ -n $output ]]; then
			echo "$output" >&3
		fi
	done
}

_cleanup-keyboard() {
	if [[ -n $_keyboard_read_pid ]]; then
		kill "$_keyboard_read_pid"
	fi
}

trap_add _cleanup-keyboard EXIT

export SOURCE_KEYBOARD=1