#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# PRAGMA: Use once and only as sourced
if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The utils can only be sourced!"; exit 1; fi
if [ -n "$SOURCE_MAP" ]; then return; fi

source "$SCRIPT_DIR/lib/utils"

# Global "Enums" for content of a map cell
MAP_CELL_WALL=1
MAP_CELL_CHEESE=2
MAP_CELL_BONUS=3
MAP_CELL_EMPTY=4

__MAP_FULL=
__MAP_CHEESE_COUNT=0
__MAP_BONUS_COUNT=0

__MAP_COLOUR_WALL="" #"\[\033[01;32m\]"
__MAP_COLOUR_DEFAULT="" #"\[\033[00m\]"

__MAP_CELL_CHEESE="∙"
__MAP_CELL_BONUS="o"
__MAP_CELL_EMPTY=" "
__MAP_CELL_TL="$__MAP_COLOUR_WALL╔$__MAP_COLOUR_DEFAULT"
__MAP_CELL_TR="╗"
__MAP_CELL_BL="╚"
__MAP_CELL_BR="╝"
__MAP_CELL_WALL_VERT="║"
__MAP_CELL_WALL_HORZ="═"

## Source in implementation that we want to try
#source "$SCRIPT_DIR/lib/map-a"
source "$SCRIPT_DIR/lib/map-b"

export SOURCE_MAP=1