#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# PRAGMA: Use once and only as sourced
if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The file can only be sourced!"; exit 1; fi
if [ -n "$SOURCE_MAP" ]; then return; fi

source "$SCRIPT_DIR/lib/utils"
source "$SCRIPT_DIR/lib/screen"
source "$SCRIPT_DIR/lib/queue"
source "$SCRIPT_DIR/lib/math"

# Global "Enums" for content of a map cell. Can be used in other modules.
MAP_CELL_WALL=1
MAP_CELL_CHEESE=2
MAP_CELL_BONUS=3
MAP_CELL_EMPTY=4
MAP_CELL_GHOST=5
MAP_CELL_PACMAN=6


## Anything below here is considered "private"
__MAP_FULL=
__MAP_CHEESE_COUNT=0
__MAP_BONUS_COUNT=0

# Colours of the map (when I get it working)
__MAP_COLOUR_WALL="" #"\033[01;32m"
__MAP_COLOUR_DEFAULT="" #"\033[00m"

# Pretty print of map content. Makes map creation easy and perhaps 
# the printing can have themes at some point
__MAP_CELL_CHEESE="∙"
__MAP_CELL_BONUS="Θ"
__MAP_CELL_EMPTY=" "
__MAP_CELL_TOP_LEFT="$__MAP_COLOUR_WALL╔$__MAP_COLOUR_DEFAULT"
__MAP_CELL_TOP_RIGHT="╗"
__MAP_CELL_BOTTOM_LEFT="╚"
__MAP_CELL_BOTTOM_RIGHT="╝"
__MAP_CELL_WALL_VERT="║"
__MAP_CELL_WALL_HORZ="═"

# Array of the actual map. 
# Seems to be the fastest way to store and access individual cells
declare -a bmap

# Queue of invalidated cells. So I only need to "repaint" certain cells
# and not the entire map. Thinks this is faster
# Must be read in pair of (col,row)
declare -a invalidatequeue
__map_is_printet=

__MAP_WIDTH=0
__MAP_HEIGHT=0


## Reads in a map file to internal structures.
# Map must be formatted according to specified syntax
# $1: path to file
map::read() {
	local filename="$1"

	[[ -f "$filename" ]] || error "Map file not found: $filename"

	mapfile -t __MAP_FULL < "$filename"
	## TODO: Pure bash
	__MAP_CHEESE_COUNT=$(printf '%s' "${__MAP_FULL[@]}" | tr -cd '*' | wc -c)
	__MAP_BONUS_COUNT=$(printf '%s' "${__MAP_FULL[@]}" | tr -cd '0' | wc -c)

	echo "__MAP_CHEESE_COUNT: $__MAP_CHEESE_COUNT" >> pacman.log
	echo "__MAP_BONUS_COUNT: $__MAP_BONUS_COUNT" >> pacman.log

	map::_get-dimentions
	map::_prettify
    map::_transform
}

map::_get-dimentions() {
	local line

	__MAP_HEIGHT="${#__MAP_FULL[@]}"
	for line in "${__MAP_FULL[@]}"; do
		__MAP_WIDTH=$(math::max "$__MAP_WIDTH" ${#line})
	done
	echo "Height: $__MAP_HEIGHT | Width: $__MAP_WIDTH" >> pacman.log
}

map::_transform() {
    local row col
	for ((row=0; row<${#__MAP_FULL[@]}; row++)); do
        local line=${__MAP_FULL[row]}
        for ((col=0; col<${#line}; col++)); do
			cell="${line:$col:1}"
            bmap[row * __MAP_WIDTH + col]="$cell"
        done
    done
}


map::_prettify() {
	local new_map=()
	local line
	for line in "${__MAP_FULL[@]}"; do
		# Pretty format cheeze
		line=${line//"*"/$__MAP_CELL_CHEESE}
		line=${line//"0"/$__MAP_CELL_BONUS}
		# Pretty format walls
		line=${line//"q"/$__MAP_CELL_TOP_LEFT}
		line=${line//"w"/$__MAP_CELL_TOP_RIGHT}
		line=${line//"a"/$__MAP_CELL_BOTTOM_LEFT}
		line=${line//"s"/$__MAP_CELL_BOTTOM_RIGHT}
		line=${line//"|"/$__MAP_CELL_WALL_VERT}
		line=${line//"-"/$__MAP_CELL_WALL_HORZ}
		# Ghost home
		line=${line//"x"/$__MAP_CELL_EMPTY}

		new_map+=("$line")
	done
	__MAP_FULL=("${new_map[@]}")
}

## Get content of a cell as printet on sceen
# $1: col
# $2: row
# $OUT: content of the cell
map::get-cell-content() {
	local col="$1"
	local row="$2"

    local cell="${bmap[row * __MAP_WIDTH + col]}"
	echo "$cell"
}

## Get the cell type at position (col, row). Represented by enums
## available outside this modules
# $1: col
# $2: row
# $OUT: cell type
map::get-cell-type() {
	local col="$1"
	local row="$2"
	local result

	local cell=$(map::get-cell-content "$col" "$row")
	case $cell in
		"$__MAP_CELL_CHEESE") result=$MAP_CELL_CHEESE;;
		"$__MAP_CELL_BONUS")  result=$MAP_CELL_BONUS;;
		"$__MAP_CELL_EMPTY")  result=$MAP_CELL_EMPTY;;
		*)	 				  result=$MAP_CELL_WALL;;
	esac

	echo "$result"
}

## Set content of a cell to be printet on sceen
# $1: col
# $2: row
# $3: new cell content
map::set-cell-content() {
	local col="$1"
	local row="$2"
	local cell_content="$3"

	local old_cell=$(map::get-cell-type "$col" "$row")

	[[ "$old_cell" == "$MAP_CELL_CHEESE" ]] && ((__MAP_CHEESE_COUNT--))
	[[ "$old_cell" == "$MAP_CELL_BONUS" ]] && ((__MAP_BONUS_COUNT--))

    bmap[row * __MAP_WIDTH + col]="$cell_content"

	invalidatequeue+=("$col")
	invalidatequeue+=("$row")
}

## Check if all cheese have been eaten on the map
# $RETURN: 0 if true, 1 if false (not all cheese are left)
map::is-clear() {
	if (( __MAP_CHEESE_COUNT == 0 )); then
		return 0
	else
		return 1
	fi
}

## Calculate a new map position given the direction of movement
## Ensures positional information is wrapped in case map boundry is met
# $1: Column
# $2: Row
# $3: Direction (left, right, up or down)
map::new-position() {
	local col="$1"
	local row="$2"
	local direction="$3"

	# Update position according to direction
	case $direction in
		left)  	((col-=1));;
		right) 	((col+=1));;
		up)		((row-=1));;
		down)	((row+=1));;
	esac

	# Wrap around edge of maps, ensures both under and over shoot is kept within maps size
	((col = (col + __MAP_WIDTH) % __MAP_WIDTH))
	((row = (row + __MAP_HEIGHT) % __MAP_HEIGHT))

	pos=("$col" "$row")
	echo "${pos[@]}"
}

map::_print-full() {
	local i col row

	for ((i=0; i<${#bmap[@]}; i++)); do
		col=$((i % __MAP_WIDTH))
		row=$((i / __MAP_WIDTH))
		screen-pos-at $((col + 1)) $((row + 1))
		printf '%s' "${bmap[$i]}"
	done
	
	__map_is_printet=1
}

# Called from the game loop to print out the map to screen
map::print-map() {
	if [[ -z $__map_is_printet ]]; then
		map::_print-full
		return
	fi

	local sz col row i
	# not sureif bash evaluates 2nd expr. on each loop - just calc it here in case
	sz=${#invalidatequeue[@]}
	for ((i=0; i<sz; i+=2)); do
		col=${invalidatequeue[$i]}
		row=${invalidatequeue[$((i+1))]}

		screen-pos-at $((col + 1)) $((row + 1))
		cell="${bmap[$((row * __MAP_WIDTH + col))]}"
		printf '%s' "$cell"
	done
	# Reset invalidation queue
	invalidatequeue=()
}

export SOURCE_MAP=1