#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# PRAGMA: Use once and only as sourced
if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The file can only be sourced!"; exit 1; fi
if [ -n "$SOURCE_MAP" ]; then return; fi

source "$SCRIPT_DIR/lib/utils"
source "$SCRIPT_DIR/lib/screen"
source "$SCRIPT_DIR/lib/math"

# Global "Enums" for content of a map cell. Can be used in other modules.
MAP_CELL_WALL=1    	# Any type of wall
MAP_CELL_CHEESE=2	# A cell with a cheese
MAP_CELL_BONUS=3	# A cell with a bonus
MAP_CELL_EMPTY=4	# An empty cell space
MAP_CELL_GHOST=5	# Cell occupied by ghost
MAP_CELL_PACMAN=6	# Cell occupied by pacman
MAP_CELL_BOX=7		# A cell space within the start box of ghosts


## Anything below here is considered "private"
__MAP_FULL=
__MAP_CHEESE_COUNT=0
__MAP_BONUS_COUNT=0

# Colours of the map (when I get it working)
__MAP_COLOUR_WALL='\e[01;34m'
__MAP_COLOUR_CHEESE='\e[38;5;180m'
__MAP_COLOUR_BONUS='\e[38;5;180m'
__MAP_COLOUR_DEFAULT='\e[00m'

# Pretty print of map content. Makes map creation easy and perhaps 
# the printing can have themes at some point
__MAP_CELL_CHEESE="${__MAP_COLOUR_CHEESE}∙${__MAP_COLOUR_DEFAULT}"
__MAP_CELL_BONUS="${__MAP_COLOUR_BONUS}⬤${__MAP_COLOUR_DEFAULT}"
__MAP_CELL_EMPTY=" "
__MAP_CELL_TOP_LEFT="${__MAP_COLOUR_WALL}╔${__MAP_COLOUR_DEFAULT}"
__MAP_CELL_TOP_RIGHT="${__MAP_COLOUR_WALL}╗${__MAP_COLOUR_DEFAULT}"
__MAP_CELL_BOTTOM_LEFT="${__MAP_COLOUR_WALL}╚${__MAP_COLOUR_DEFAULT}"
__MAP_CELL_BOTTOM_RIGHT="${__MAP_COLOUR_WALL}╝${__MAP_COLOUR_DEFAULT}"
__MAP_CELL_WALL_VERT="${__MAP_COLOUR_WALL}║${__MAP_COLOUR_DEFAULT}"
__MAP_CELL_WALL_HORZ="${__MAP_COLOUR_WALL}═${__MAP_COLOUR_DEFAULT}"

# Array of the actual map. 
# Seems to be the fastest way to store and access individual cells
declare -a __MAP_DEFAUT_MAP
declare -a __MAP_PRETTY_MAP

# Queue of invalidated cells. So I only need to "repaint" certain cells
# and not the entire map. Thinks this is faster
# Must be read in pair of (col,row)
declare -a invalidatequeue
__map_is_printet=

__MAP_WIDTH=0
__MAP_HEIGHT=0


## Reads in a map file to internal structures.
# Map must be formatted according to specified syntax
# $1: path to file
map::read() {
	local filename="$1"
	[[ -f "$filename" ]] || error "Map file not found: $filename"

	local input_map
	mapfile -t input_map < "$filename"

	map::_get-dimentions "${input_map[@]}"
    map::_transform "${input_map[@]}"
	map::_prettify
}

map::_get-dimentions() {
	local input_map=("$@")

	__MAP_HEIGHT="${#input_map[@]}"

	local line
	for line in "${input_map[@]}"; do
		__MAP_WIDTH=$(math::max "$__MAP_WIDTH" ${#line})
	done

	log "Height: $__MAP_HEIGHT | Width: $__MAP_WIDTH"
}

map::_transform() {
	local input_map=("$@")

    local row col cell
	for ((row=0; row<${#input_map[@]}; row++)); do
        local line=${input_map[row]}
        for ((col=0; col<${#line}; col++)); do
			cell="${line:$col:1}"
            __MAP_DEFAUT_MAP[row * __MAP_WIDTH + col]="$cell"
        done
    done
}


map::_prettify() {
	local cell size
	
	size=${#__MAP_DEFAUT_MAP[@]}
	for ((idx=0; idx<size; idx++)); do
		cell="${__MAP_DEFAUT_MAP[idx]}"

		case "$cell" in
			"*") 
				((__MAP_CHEESE_COUNT++))
				cell=$__MAP_CELL_CHEESE
				;;
			"0")
				((__MAP_BONUS_COUNT++)) 
				cell=$__MAP_CELL_BONUS
				;;
			"q") 
				cell=$__MAP_CELL_TOP_LEFT
				;;
			"w") 
				cell=$__MAP_CELL_TOP_RIGHT
				;;
			"a") 
				cell=$__MAP_CELL_BOTTOM_LEFT
				;;
			"s") 
				cell=$__MAP_CELL_BOTTOM_RIGHT
				;;
			"|") 
				cell=$__MAP_CELL_WALL_VERT
				;;
			"-") 
				cell=$__MAP_CELL_WALL_HORZ
				;;
			"x") 
				cell=$__MAP_CELL_EMPTY
				;;
		esac

		__MAP_PRETTY_MAP[idx]=$cell
	done

	log "__MAP_CHEESE_COUNT: $__MAP_CHEESE_COUNT"
	log "__MAP_BONUS_COUNT: $__MAP_BONUS_COUNT"
}

map::_get-content() {
	local -n input=$1
	local col="$2"
	local row="$3"

    local cell="${input[row * __MAP_WIDTH + col]}"
	echo "$cell"
}

## Get content of a cell as printet on sceen
# $1: col
# $2: row
# $OUT: content of the cell
map::get-cell-content() {
	local col="$1"
	local row="$2"

    local cell=$(map::_get-content __MAP_PRETTY_MAP "$col" "$row")
	echo "$cell"
}

## Get the cell type at position (col, row). Represented by enums
## available outside this modules
# $1: col
# $2: row
# $OUT: cell type
map::get-cell-type() {
	local col="$1"
	local row="$2"
	local result

	local cell=$(map::_get-content __MAP_DEFAUT_MAP "$col" "$row")
	case $cell in
		" ")
			result=$MAP_CELL_EMPTY;;
		"*")
			result=$MAP_CELL_CHEESE;;
		"0")
			result=$MAP_CELL_BONUS;;
		"q" | "w" | "a" | "s" | "|" | "-")
			result=$MAP_CELL_WALL;;
		"x") 
			result=$MAP_CELL_BOX;;
	esac

	echo "$result"
}

## Set content of a cell to be printet on sceen
# $1: col
# $2: row
# $3: new cell content
map::set-cell-content() {
	local col="$1"
	local row="$2"
	local cell_content="$3"

    __MAP_PRETTY_MAP[row * __MAP_WIDTH + col]="$cell_content"

	invalidatequeue+=("$col")
	invalidatequeue+=("$row")
}

## Check if all cheese have been eaten on the map
# $RETURN: 0 if true, 1 if false (not all cheese are left)
map::is-clear() {
	if (( __MAP_CHEESE_COUNT == 0 )); then
		return 0
	else
		return 1
	fi
}

## Calculate a new map position given the direction of movement
## Ensures positional information is wrapped in case map boundry is met
# $1: Column
# $2: Row
# $3: Direction (left, right, up or down)
map::new-position() {
	local col="$1"
	local row="$2"
	local direction="$3"

	# Update position according to direction
	case $direction in
		left)  	((col-=1));;
		right) 	((col+=1));;
		up)		((row-=1));;
		down)	((row+=1));;
	esac

	# Wrap around edge of maps, ensures both under and over shoot is kept within maps size
	((col = (col + __MAP_WIDTH) % __MAP_WIDTH))
	((row = (row + __MAP_HEIGHT) % __MAP_HEIGHT))

	pos=("$col" "$row")
	echo "${pos[@]}"
}

map::_print-full() {
	local i j col row

	local s
	for ((row=0; row<__MAP_HEIGHT; row++)); do
		s=""

		for ((col=0; col<__MAP_WIDTH; col++)); do
			s+="${__MAP_PRETTY_MAP[row * __MAP_WIDTH + col]}"
		done

		printf "$s\n"
	done
	
	__map_is_printet=1
}

# Called from the game loop to print out the map to screen
map::print-map() {
	if [[ -z $__map_is_printet ]]; then
		map::_print-full
		return
	fi

	local sz col row i
	# not sureif bash evaluates 2nd expr. on each loop - just calc it here in case
	sz=${#invalidatequeue[@]}
	for ((i=0; i<sz; i+=2)); do
		col=${invalidatequeue[$i]}
		row=${invalidatequeue[$((i+1))]}

		screen::pos-at $((col + 1)) $((row + 1))
		cell="${__MAP_PRETTY_MAP[$((row * __MAP_WIDTH + col))]}"
		printf "$cell"
	done
	# Reset invalidation queue
	invalidatequeue=()
}

export SOURCE_MAP=1