#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

declare -a bmap
declare -a invalidatequeue
__map_is_printet=

_MAP_WIDTH=29
_MAP_HEIGHT=31

source "$SCRIPT_DIR/lib/screen"
source "$SCRIPT_DIR/lib/queue"

## Reads in a map file, stores in the FULL_MAP array
# $1: path to file
map-read() {
	local filename="$1"

	[[ -f "$filename" ]] || error "Map file not found: $filename"

	mapfile __MAP_FULL < "$filename"
	__MAP_CHEESE_COUNT=$(printf '%s' "${__MAP_FULL[@]}" | tr -cd '*' | wc -c)
	__MAP_BONUS_COUNT=$(printf '%s' "${__MAP_FULL[@]}" | tr -cd 'o' | wc -c)

	echo "__MAP_CHEESE_COUNT: $__MAP_CHEESE_COUNT" >> /tmp/pacman.log
	echo "__MAP_BONUS_COUNT: $__MAP_BONUS_COUNT" >> /tmp/pacman.log

	_map-prettify
    _map-transform

	# echo "${bmap[*]}"
	# exit 1
}

_map-transform() {
    local row col
	for ((row=0; row<${#__MAP_FULL[@]}; row++)); do
        local line=${__MAP_FULL[row]}
		# echo "ROW: $row | Line# ${#line}"
        for ((col=0; col<${#line}; col++)); do
			cell="${line:$col:1}"
            bmap[row * _MAP_WIDTH + col]="$cell"
			# echo "$cell"
        done
    done
	# exit 1
}


_map-prettify() {
	local new_map=()
	local line
	for line in "${__MAP_FULL[@]}"; do
		# Pretty format cheeze
		line=${line//"*"/$__MAP_CELL_CHEESE}
		line=${line//"o"/$__MAP_CELL_BONUS}
		# Pretty format walls
		line=${line//"q"/$__MAP_CELL_TL}
		line=${line//"w"/$__MAP_CELL_TR}
		line=${line//"a"/$__MAP_CELL_BL}
		line=${line//"s"/$__MAP_CELL_BR}
		line=${line//"|"/$__MAP_CELL_WALL_VERT}
		line=${line//"-"/$__MAP_CELL_WALL_HORZ}

		new_map+=("$line")
	done
	__MAP_FULL=("${new_map[@]}")
}

map-get-cell-content() {
	local col="$1"
	local row="$2"

    local cell="${bmap[$((row * _MAP_WIDTH + col))]}"
	echo "$cell"
}

map-get-cell-type() {
	local col="$1"
	local row="$2"
	local result

	local cell=$(map-get-cell-content "$col" "$row")
	case $cell in
		"$__MAP_CELL_CHEESE") result=$MAP_CELL_CHEESE;;
		"$__MAP_CELL_BONUS")  result=$MAP_CELL_BONUS;;
		"$__MAP_CELL_EMPTY")  result=$MAP_CELL_EMPTY;;
		*)	 				  result=$MAP_CELL_WALL;;
	esac

	echo "$result"
}

map-set-cell-content() {
	local col="$1"
	local row="$2"
	local cell_content="$3"

	local old_cell=$(map-get-cell-type "$col" "$row")

	[[ "$old_cell" == "$MAP_CELL_CHEESE" ]] && ((__MAP_CHEESE_COUNT--))
	[[ "$old_cell" == "$MAP_CELL_BONUS" ]] && ((__MAP_BONUS_COUNT--))

    bmap[ row * _MAP_WIDTH + col ]="$cell_content"

	invalidatequeue+=("$col")
	invalidatequeue+=("$row")
}

map-is-clear() {
	if (( __MAP_CHEESE_COUNT == 0 )); then
		return 0
	else
		return 1
	fi
}

_map-print-full() {
	local i

	for ((i=0; i<${#bmap[@]}; i++)); do
		local col=$((i % _MAP_WIDTH))
		local row=$((i / _MAP_WIDTH))
		screen-pos-at $((col + 1)) $((row + 1))
		printf '%s' "${bmap[$i]}"
	done
	
	__map_is_printet=1
}

map-print-map() {
	if [[ -z $__map_is_printet ]]; then
		_map-print-full
		return
	fi

	local sz col row i
	sz=${#invalidatequeue[@]}
	for ((i=0; i<sz; i+=2)); do
		col=${invalidatequeue[$i]}
		row=${invalidatequeue[$((i+1))]}

		screen-pos-at $((col + 1)) $((row + 1))
		cell="${bmap[$((row * _MAP_WIDTH + col))]}"
		printf '%s' "$cell"
	done
	invalidatequeue=()
}
