#!/bin/bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# PRAGMA: Use once and only as sourced
if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The timer can only be sourced!"; exit 1; fi
if [ ! -z "${SOURCE_QUEUE:-}" ]; then return; fi


## Push new item in the queue
# $1: Name of the queue variable
# $2: Element to push
# $3: (Optional) max size of queue - pop oldest element off
queue-push() {
    local -n queue="$1"
    local element="$2"
    local max_size=0
    [[ $# -eq 3 ]] && max_size="$3"

    queue+=("$element")

    # Pop oldest element if max_size defined and reached
    if (( max_size > 0)) && ((${#queue[@]} > max_size)); then
        queue=("${queue[@]:1}")
    fi
}

## Push new item in the queue
# $1: Name of the queue variable
# $OUT: The elemt popped
queue-pop() {
    local -n queue="$1"
    local result

    result="${queue[0]}"
    queue=("${queue[@]:1}")

    echo "$result"
}


SOURCE_QUEUE=1