#!/bin/bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# PRAGMA: Use once and only as sourced
if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The statusbar can only be sourced!"; exit 1; fi
if [ ! -z "${SOURCE_STATUSBAR:-}" ]; then return; fi

## Configurable parameters
# Charater to show is the message is too long
STATUSBAR_POSTFIX="..."

## IMPLEMENTATION
# Use screen for getting a reserved line at the bottom
source "${SCRIPT_DIR}/lib/screen"

# Setup the statusbar
statusbar-setup() {
    screen_reserve_line "bottom"
    _statusbar_line=$SCREEN_LINE
}

## Update the statusbar content
# $1: The message to put on the statusbar
statusbar-update() {
    local msg="$1"
    local len=${#msg}

    if (( len > COLUMNS )); then
        # Slice string to allow for STATUSBAR_POSTFIX at the end
        local postfix_len=${#STATUSBAR_POSTFIX}
        local msg_cut_pos=$((SCREEN_WIDTH - postfix_len))
        msg=${msg:0:$msg_cut_pos}$STATUSBAR_POSTFIX
    fi

    screen_write_to_reserved_line "bottom" "$_statusbar_line" "$msg"
}


export SOURCE_STATUSBAR=1

