#!/usr/bin/env bash
#
# MIT License
#
# Copyright (c) 2026 Torsten Bonde Christiansen
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

# PRAGMA: Use once and only as sourced
if [ "${BASH_SOURCE[0]}" -ef "$0" ]; then echo "The utils can only be sourced!"; exit 1; fi
if [ -n "$SOURCE_UTILS" ]; then return; fi


## Output error message to STDOUT and halts program with exit code 1
# $1: message to output
error() {
    message="$1"
    echo "$message" > /dev/stderr
    exit 1
}

fatal() {
    error "$1"
}

## Create a temporary fifi pipe
# $OUTPUT: path of create pipe
mktemp_fifo() {
    local pipe
    pipe="$(mktemp -u)"

    while [[ -e "$pipe" ]]; do
        pipe="$(mktemp -u)"
    done

    mkfifo "$pipe" || fatal "failed to create pipe $PIPE"
    echo "$pipe"
}

export SOURCE_UTILS=1